version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_pet_store
    hostname: localhost
    environment:
      POSTGRES_DB: pet_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pet_store_network

networks:
  pet_store_network:
    driver: bridge

volumes:
  postgres_data: 